7.32d update for hero level up and item choices
adamqqqplay/dota2ai pull request #75
Opened 2023-01-24 13:04 UTC by ArcherWayne

7.32d changelog
1. bots now can correctly use bloodstone and eternal shroud. 
2. updated the ability/talent levelup and the item choice for the following heros:
   1. razor
   2. viper
   3. sniper
   4. juggernaut
   5. zeus
   6. huskar
   7. phantom assassin
   8. crystal maiden
   9. ember spirit
   10. centaur warrunner
   11. venomancer
   12. doom bringer
   13. slardar
   14. silencer
   15. legion commander
   16. riki
   17. clinkz
   18. leshrac
   19. drow ranger
   20. dragon knight
   21. shadow fiend
   22. axe
   23. bloodseeker
   24. bristleback
   25. spectre
   26. anti-mage
   27. facelss void
   28. bounty hunter
   29. pudge
   30. witch docter
   31. bounty hunter
   32. disrupter
   33. enchantress
   34. magnus
   35. monkey king
   36. weaver
   37. phantom lancer
   38. timbersaw
   39. tusk

2023-01-28 04:29 UTC, ArcherWayne commented
git commit --amend

2023-01-28 05:29 UTC, adamqqqplay commented
I think it would be better to merge changelog_7.32d.md into changelog_en.txt

2023-01-30 07:11 UTC, adamqqqplay requested changes
Thanks for your contribution, but you need to delete unnecessary code and format all code before merging.

2023-01-30 07:11 UTC, adamqqqplay commented on util/ItemUsageSystem.lua
> +    -- zjc:test start
Please delete unnecessary code in this file

2023-01-30 07:11 UTC, adamqqqplay commented on hero_selection.lua
>  local hero_pool_test = {
hero_pool_test should not be used in non-test environments.

2023-01-30 07:11 UTC, adamqqqplay commented on item_purchase_silencer.lua
> +    "item_magic_stick",
You could format these codes first

2023-01-30 07:11 UTC, adamqqqplay commented on item_purchase_tusk.lua
> +    "item_magic_stick",
You could format these codes first.

2023-01-31 13:39 UTC, adamqqqplay approved these changes

2023-01-31 13:39 UTC, adamqqqplay commented
LGTM

2023-01-31 13:40 UTC, merged